FROM ubuntu:18.04
MAINTAINER tom <stainer.tom@gmail.com>

# Build-time metadata as defined at http://label-schema.org
ARG PROJECT_NAME
ARG BUILD_DATE
ARG VCS_REF
ARG VERSION
LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.name="$PROJECT_NAME" \
      org.label-schema.description="Ubuntu docker image for phoebus-base" \
      org.label-schema.url="http://github.com/thomasms" \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.vcs-url="https://github.com/thomasms" \
      org.label-schema.vendor="" \
      org.label-schema.version=$VERSION \
      org.label-schema.license="BSD-3-Clause" \
      org.label-schema.schema-version="1.0"

ENV PHOEBUS_BASE /epics/phoebus
ENV PHOEBUS_DEV_NAME phoebus-dev
ENV PHOEBUS_DEV ${PHOEBUS_BASE}/${PHOEBUS_DEV_NAME}

ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64/

COPY packages packages

# Install additional packages
RUN apt-get update -qq \
 && ln -sf /usr/share/zoneinfo/UTC /etc/localtime \
 && apt-get -y install $(cat packages) \
 && localedef -i en_US -f UTF-8 en_US.UTF-8 \
 && rm -rf /packages /var/lib/apt/lists/* \
 && mkdir -p ${PHOEBUS_BASE} && cd ${PHOEBUS_BASE} && git clone https://github.com/thomasms/phoebus ${PHOEBUS_DEV_NAME} \
 && cd ${PHOEBUS_DEV_NAME} && mvn -DskipTests=true clean install \
 # rename binaries
 && cd ${PHOEBUS_DEV}/phoebus-product/target && export PHOEBUS_JAR=`echo product-*.jar` && mv ${PHOEBUS_JAR} product.jar

WORKDIR ${PHOEBUS_DEV}

# Hack to fix issues with libGL, see: https://github.com/jessfraz/dockerfiles/issues/253
RUN apt-get update && apt install -y nvidia-340 mesa-utils && glxgears || true

ENTRYPOINT ["java", "-jar", "phoebus-product/target/product.jar", "-server", "4918"]
